version: '3.8'
services:
  app:
    image: kubik/salary-calculator
    build: .
    container_name: salary-calculator
    restart: unless-stopped
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
